[versions]
jackson = "2.20.1"
org-jetbrains-kotlinx = "1.10.2"

[libraries]
gradleplugin-jreleaser = "org.jreleaser:org.jreleaser.gradle.plugin:1.21.0"
htmlunit = "org.htmlunit:htmlunit:4.18.0"
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
jackson-datatype-jdk8 = { module = "com.fasterxml.jackson.datatype:jackson-datatype-jdk8", version.ref = "jackson" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin", version.ref = "jackson" }
javapoet = "com.palantir.javapoet:javapoet:0.7.0"
jsoup = "org.jsoup:jsoup:1.21.2"
jspecify = "org.jspecify:jspecify:1.0.0"
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "org-jetbrains-kotlinx" }
kotlinx-coroutines-jdk8 = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-jdk8", version.ref = "org-jetbrains-kotlinx" }
okhttp = "com.squareup.okhttp3:okhttp:5.2.1"

# For buildSrc logic
#gradleplugin-jreleaser = { module = "org.jreleaser:org.jreleaser.gradle.plugin", version ="1.15.0" }
[plugins]
#https://github.com/melix/jmh-gradle-plugin
jmh = "me.champeau.jmh:0.7.3"
jreleaser = "org.jreleaser:1.21.0"
shadow = "com.gradleup.shadow:9.2.2"
versions = "com.github.ben-manes.versions:0.53.0"
versions-catalog = "nl.littlerobots.version-catalog-update:1.0.1"
